.TH PT "1" "June 2026" "pt 1.0.0" "User Commands"
.SH NAME
pt \- Periodic table
.SH SYNOPSIS
.SY
.B pt
[\fI\,OPTION\/\fR]... [\fI\,ELEMENT\/\fR]...
.br
.B pt
[\fI\,OPTION\/\fR]...
.YS
.SH DESCRIPTION
.B pt
is a utility to interface data about the chemical elements.
Given \fIELEMENT\fR, print configurable information about the physical properties of  that \fIELEMENT\fR, such as atomic mass, phase at STP, or the first ionization energy.
If no ELEMENT given, print periodic table.
If ELEMENT is '\-', read standard input.
.SH OPTIONS
Mandatory options to long options are mandatory for short options too.
.SS "GENERAL OPTIONS"
.TP
\fB\-H\fR, \fB\-\-no\-header\fR
Disable header information.
When outputting the full table, this disables the display of period and group headers.
Instead when outputting element information, this disables a header line printed when the program starts labelling each column of information. 
.TP
\fB\-l\fR, \fB\-\-loose\-exit\-status\fR
Change the behavior of the exit status.
Normally, the program will exit non-zero if any invalid input is provided.
This flag will change the behavior such that the program will only exit non-zero if a fatal error is encountered.
.TP
\fB\-q\fR, \fB\-\-silent\fR
Do not output error messages.
.PP
.SS "INFORMATION FLAGS"
.PP
These options select what information is displayed when the full table is not displayed.
Information is output in the order provided here, not in the order flags are provided, meaning flags may be specified in any order.
If no information flags are provided, by default Symbol, Number, and Atomic Mass are displayed.
.TP
\fB\-s\fR, \fB\-\-symbol\fR
Two-letter IUPAC element symbol (e.g. 'He')
.TP
\fB\-n\fR, \fB\-\-number\fR
Atomic number; the number of protons the element has.
.TP
\fB\-S\fR, \fB\-\-name\fR
Common element name.
Standard English names are used.
.TP
\fB\-w\fR, \fB\-\-mass\fR
Atomic mass, or, in the case of radioactive elements, the mass number of the most stable isotope, in AMU.
.TP
\fB\-d\fR, \fB\-\-density\fR
Mass density, in kg/m^3.
.TP
\fB\-t\fR, \fB\-\-type\fR
Element type; typically which section of the periodic table the element is found in.
.TP
\fB\-p\fR, \fB\-\-phase\fR
Phase of matter at STP.
.TP
\fB\-m\fR, \fB\-\-melting\-point\fR
Melting point at standard pressure, in Kelvin.
.TP
\fB\-M\fR, \fB\-\-boiling\-point\fR
Boiling point at standard pressure, in Kelvin.
.TP
\fB\-i\fR, \fB\-\-ionization\fR
First ionization energy, in kJ/mol.
.TP
\fB\-e\fR, \fB\-\-electronegativity\fR
Element electronegativity, on the Pauling scale.
.TP
\fB\-c\fR, \fB\-\-electron\-configuration\fR
Atomic electron configuration.
Configurations are in 'short' form, abbreviated to the last noble gas.
.TP
\fB\-\-all\fR
Shortcut for enabling all information.
Mostly useful in making a dump to use elsewhere.
.SS "GETTING HELP"
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a short help message and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit.
.SH AUTHOR
Written by Jack R. Uteg.
.SH COPYRIGHT
Copyright \(co 2026 Jack Renton Uteg.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.PP
Certain sections Copyright \(co Stack Exchange users; used CC-BY-SA 4.0. See source files for details.
.PP
Data Copyright \(co Dedolist 'https://raw.githubusercontent.com/dedolist/open-data/refs/heads/master/data/science/periodic-table-detailed/data.csv', used according to the terms of the Open Data Commons Public Domain Dedication License v1.0.
.SH "SEE ALSO"
