args	"-F pt -c g.c -H g.h -uELEMENT --func-name ggo --show-required --default-optional --no-help --no-version -G"

package "pt"
version "1.0.0"

description	"Print information about the chemical elements.\nIf no ELEMENT given, print periodic table.\nIf ELEMENT is '-', read standard input.\nSpecify element as atomic number, symbol, or full name."

section "Program options"
option	"no-header"	H	"Do not print header information"
option	"loose-exit-status" l "Exit with 0 even if invalid input encountered"
option  "silent"    q   "Do not output error messages"
section	"Output options"
option	"symbol"	s	"IUPAC element symbol"
option	"number"	n	"Atomic number"
option	"name"	S	"Common element name"
option	"mass"	w	 "Atomic mass/weight/Most stable isotope"
option	"density"	d	"Mass density"
option	"type"	t	 "Element type"
option	"phase" p	"Element phase at STP"
option	"melting-point" m	"Element melting point at standard pressure"
option	"boiling-point" M	"Element boiling point at standard pressure"
option	"ionization"	i	"First ionization energy"
option	"electronegativity" e	"Element electronegativity"
option  "electron-configuration" c "Short atomic electron configuration"
option  "all"   -   "All information enabled"
text	"Information is output in the order the options are given here."
section	"Getting help"
option	"help" h "Print this help message and exit"
option	"version" v "Print version information and exit"
text	"\nTry 'man pt' for more information."

versiontext	"Copyright (C) 2026 Jack Renton Uteg.\nLicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n\nWritten by Jack R. Uteg.\n\nElement Data Copyright \(co Dedolist, at <https://raw.githubusercontent.com/dedolist/open-data/refs/heads/master/data/science/periodic-table-detailed/data.csv>\nLicense ODC-PDDL: Open Data Commons Public Domain Dedication License v1.0 <https://opendatacommons.org/licenses/pddl/1-0/index.html>.\nModified from the original in a manner not endorsed by Dedolist."
